### PR TITLE
fix: issue#710 Shop name not persisting on Mobile Nav

### LINKED ISSUE #710: Shop name not persisting on Mobile Nav
Type: **minor**

**Describe the bug**
Shop name is not persisting on the mobile navigation.

**To Reproduce**
1. Set shop name via admin app.
2. Observe shop name displays in Header.
3. Shrink viewport size to display mobile navigation.
4. Open mobile navigation and observe shop name

**Expected behavior**
Shop name appears consistently across the app.

**Screenshots**

Peek 2020-07-28 16-01

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Ungoogled Chromium
 - Version: Version 84.0.4147.89 (Official Build) Arch Linux (64-bit)

**Additional context**
Observed on `release-next-v3.2.0` branch. `shop` prop is `undefined` in `NavigationMobile`.

### PR DESCRIPTION
**Pull request by ihalton**
Resolves #710 
Impact: **minor**
Type: **bugfix**

## Issue
Description of the issue this PR is solving, why it's happening, and how to reproduce it. This may differ from the original ticket as you now have more information at your disposal.

## Solution
Summarize your solution to the problem. Please include short descriptions of any solutions you tested before arriving at your final solution. This will help reviewers know why you decided to solve this problem in this particular way and will speed up the review process.

If you're solving a UIX related issue, please attach screen-caps or gifs showing how your solution differs from the issue.

## Breaking changes
If you have a breaking changes, list them here, otherwise list none.

Examples of breaking changes include changing file names, moving files, deleting files, renaming functions or exports, or changes to code which might cause previous versions of Reaction or third-party code not to work as expected.

Note any work that you did to mitigate the effect of any breaking changes such as creating migrations, deprecation warnings, etc.

## Testing
1. List the steps needed for testing your change in this section.
2. Assume that testers already know how to start the app, and do the basic setup tasks.
3. Be detailed enough that someone can work through it without being too granular

More detail for what each of these sections should include are available in our [Contributing Docs](https://docs.reactioncommerce.com/reaction-docs/trunk/contributing-to-reaction)

### CODE REVIEW

**Comment by ghost** [comment]
@janus-reith could you please review? This fixes a known issue with the logo

**Review by janus-reith — APPROVED** [review]
LGTM

**Review by Akarshit — APPROVED** [review]

File: components/Header/Header.js [hunk 1]
```diff
@@ -84,7 +84,7 @@ class Header extends Component {
           <AccountDropdown />
           <MiniCart />
         </Toolbar>
-        <NavigationMobile />
+        <NavigationMobile shop={shop}/>
```
Comment (ghost) [inline components/Header/Header.js:87]: I saw an issue similar to this Re: sitemaps in a different project. Neither issue would get picked up by TypeScript static analysis if the project were converted. As @janus-reith mentioned in #709 a conversion may not be suitable for front-end until other repos in the org are in line with a conversion initiative.
